### PR TITLE
Ruby 2 version

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@tagomoris this is the continuation of #26 - a version that is ruby2 only

ありがとう ございました 🙇

**Comment by tagomoris** [comment]
This change includes update of gem version only, without anything like dependency updates.

**Comment by ppp0** [comment]
Yes .. Actually travis fails with

```
Installing fluentd 0.14.0
Gem::InstallError: fluentd requires Ruby version >= 2.1.
```

So I removed 2.0.0

**Comment by ppp0** [comment]
Also I think it would be weird to have a minor version than this supporting older ruby envs.. That's why I thought to bump it again. PR is closed I can't push changes

**Comment by tagomoris** [comment]
Is this change almost same with #26, right?
Please add commits on it, and modify its title, rather than stack another pull-requests.

**Comment by ppp0** [comment]
Well,  #26 is a fix to support older ruby envs

I believe a new PR is needed to bump the version again and to correct the failure on travis. But up to you

**Comment by tagomoris** [comment]
OK, go forward to do it.

**Comment by ppp0** [comment]
👍 thank you

Depends on #26

**Comment by ppp0** [comment]
Completely solved in #26

**Pull request closed without merging**
