### PR TITLE
Follow up Travis environment changes

### PR DESCRIPTION
**Pull request by cosmo0920**

### CODE REVIEW

**Comment by tagomoris** [comment]
Could you add `sudo: false` for more fast tests?

**Comment by cosmo0920** [comment]
Sure, I'll do it.

**Comment by okkez** [comment]
Could you drop Ruby 1.9.3 from .travis.yml.

See https://github.com/tagomoris/fluent-plugin-forest/pull/20#issuecomment-174458063

**Comment by okkez** [comment]
Thanks!

**Pull request merged**
