### PR TITLE
Release backward compatible version (rb 1.9.x)

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
We're having a few problems on our CI with Debian Wheezy nodes, where ruby is still 1.9.3. Before gem fluentd v0.14.0 was released all was working. (see https://github.com/cargomedia/puppet-packages/pull/1347 and https://github.com/cargomedia/puppet-packages/pull/1342)

I added a contraint in the gemspec so that fluentd  ~>0.12.0 is required. This should allow to use the plugin on Debian Wheezy

For ruby 2 I suggest to bump the version again and to release without contraint

@tagomoris I hope you are fine with this method. Thank you very much for looking into it!

**Comment by tagomoris** [comment]
It's acceptable for me to restrict related versions smaller than `0.14.0` (`<= 0.14.0`).
But It's unacceptable to allow to run on ruby 1.9.3. It's not maintained by ruby community, so that I cannot pay any attention about it.

**Comment by ppp0** [comment]
OK, I can remove this!

**Comment by ppp0** [comment]
See also This is because of https://github.com/fluent/fluentd/issues/888#issuecomment-223298220

**Comment by ppp0** [comment]
See https://github.com/y-ken/fluent-plugin-sentry/pull/7/files/44390055248a459d4e907e1f265fbe7a29f170e6#r65691067

@tagomoris Do you like this, too?

**Comment by tagomoris** [comment]
@ppp0 Sorry, I can't understand what you mean. Please say again in your word?

**Comment by ppp0** [comment]
Is it OK to add a ruby version switch as in the PR so that one doesn't need to tag an additional version?

**Comment by ppp0** [comment]
Closing as without intended effect. We will phase out Debian Wheezy

**Pull request closed without merging**
